apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evo-ai-backend-hpa
  namespace: client-saas
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evo-ai-backend
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      # Esperar 60 segundos antes de diminuir o número de pods
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      # Políticas para limitar a escala rápida durante inicialização
      stabilizationWindowSeconds: 120
      policies:
      # Adicionar no máximo 1 pod a cada 60 segundos
      - type: Pods
        value: 1
        periodSeconds: 60
      # Ou aumentar no máximo 50% a cada 30 segundos
      - type: Percent
        value: 50
        periodSeconds: 30
      # Usar a menor das duas restrições (a mais conservadora)
      selectPolicy: Min